name: UnitTests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  basics:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: test
        run: mvn -B test -pl basics -am -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  object-oriented-programming:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2
        - name: set up JDK 21
          uses: actions/setup-java@v1
          with:
            java-version: 21
        - name: test
          run: mvn -B test -pl object-oriented-programming -am -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  collections:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: test
        run: mvn -B test -pl collections -am -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
